package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class App implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.logo
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.bundle_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String bundleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.platform
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.id
     *
     * @return the value of app.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.id
     *
     * @param id the value for app.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.logo
     *
     * @return the value of app.logo
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.logo
     *
     * @param logo the value for app.logo
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setLogo(String logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.name
     *
     * @return the value of app.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.name
     *
     * @param name the value for app.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.bundle_id
     *
     * @return the value of app.bundle_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getBundleId() {
        return bundleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.bundle_id
     *
     * @param bundleId the value for app.bundle_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setBundleId(String bundleId) {
        this.bundleId = bundleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.platform
     *
     * @return the value of app.platform
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.platform
     *
     * @param platform the value for app.platform
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.create_time
     *
     * @return the value of app.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.create_time
     *
     * @param createTime the value for app.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app.update_time
     *
     * @return the value of app.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app.update_time
     *
     * @param updateTime the value for app.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}