package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class AppPatchFlow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_patch_flow.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_patch_flow.app_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_patch_flow.app_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer appVersionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_patch_flow.patch_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer patchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_patch_flow.status
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_patch_flow.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_patch_flow.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_patch_flow.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_patch_flow.id
     *
     * @return the value of app_patch_flow.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_patch_flow.id
     *
     * @param id the value for app_patch_flow.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_patch_flow.app_id
     *
     * @return the value of app_patch_flow.app_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_patch_flow.app_id
     *
     * @param appId the value for app_patch_flow.app_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_patch_flow.app_version_id
     *
     * @return the value of app_patch_flow.app_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getAppVersionId() {
        return appVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_patch_flow.app_version_id
     *
     * @param appVersionId the value for app_patch_flow.app_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setAppVersionId(Integer appVersionId) {
        this.appVersionId = appVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_patch_flow.patch_id
     *
     * @return the value of app_patch_flow.patch_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getPatchId() {
        return patchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_patch_flow.patch_id
     *
     * @param patchId the value for app_patch_flow.patch_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setPatchId(Integer patchId) {
        this.patchId = patchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_patch_flow.status
     *
     * @return the value of app_patch_flow.status
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_patch_flow.status
     *
     * @param status the value for app_patch_flow.status
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_patch_flow.descr
     *
     * @return the value of app_patch_flow.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_patch_flow.descr
     *
     * @param descr the value for app_patch_flow.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_patch_flow.create_time
     *
     * @return the value of app_patch_flow.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_patch_flow.create_time
     *
     * @param createTime the value for app_patch_flow.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_patch_flow.update_time
     *
     * @return the value of app_patch_flow.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_patch_flow.update_time
     *
     * @param updateTime the value for app_patch_flow.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}