package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class AppPluginFlow implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_plugin_flow.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_plugin_flow.app_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_plugin_flow.app_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer appVersionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_plugin_flow.plugin_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer pluginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_plugin_flow.plugin_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer pluginVersionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_plugin_flow.status
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_plugin_flow.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_plugin_flow.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_plugin_flow.id
     *
     * @return the value of app_plugin_flow.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_plugin_flow.id
     *
     * @param id the value for app_plugin_flow.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_plugin_flow.app_id
     *
     * @return the value of app_plugin_flow.app_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_plugin_flow.app_id
     *
     * @param appId the value for app_plugin_flow.app_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_plugin_flow.app_version_id
     *
     * @return the value of app_plugin_flow.app_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getAppVersionId() {
        return appVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_plugin_flow.app_version_id
     *
     * @param appVersionId the value for app_plugin_flow.app_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setAppVersionId(Integer appVersionId) {
        this.appVersionId = appVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_plugin_flow.plugin_id
     *
     * @return the value of app_plugin_flow.plugin_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getPluginId() {
        return pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_plugin_flow.plugin_id
     *
     * @param pluginId the value for app_plugin_flow.plugin_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setPluginId(Integer pluginId) {
        this.pluginId = pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_plugin_flow.plugin_version_id
     *
     * @return the value of app_plugin_flow.plugin_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getPluginVersionId() {
        return pluginVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_plugin_flow.plugin_version_id
     *
     * @param pluginVersionId the value for app_plugin_flow.plugin_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setPluginVersionId(Integer pluginVersionId) {
        this.pluginVersionId = pluginVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_plugin_flow.status
     *
     * @return the value of app_plugin_flow.status
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_plugin_flow.status
     *
     * @param status the value for app_plugin_flow.status
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_plugin_flow.create_time
     *
     * @return the value of app_plugin_flow.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_plugin_flow.create_time
     *
     * @param createTime the value for app_plugin_flow.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_plugin_flow.update_time
     *
     * @return the value of app_plugin_flow.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_plugin_flow.update_time
     *
     * @param updateTime the value for app_plugin_flow.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}