package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class PackageVersion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.package_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.build_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer buildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.online_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String onlineUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.update_way
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String updateWay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_version.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.id
     *
     * @return the value of package_version.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.id
     *
     * @param id the value for package_version.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.package_id
     *
     * @return the value of package_version.package_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.package_id
     *
     * @param packageId the value for package_version.package_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.version
     *
     * @return the value of package_version.version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.version
     *
     * @param version the value for package_version.version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.build_id
     *
     * @return the value of package_version.build_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.build_id
     *
     * @param buildId the value for package_version.build_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setBuildId(Integer buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.online_url
     *
     * @return the value of package_version.online_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getOnlineUrl() {
        return onlineUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.online_url
     *
     * @param onlineUrl the value for package_version.online_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setOnlineUrl(String onlineUrl) {
        this.onlineUrl = onlineUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.update_way
     *
     * @return the value of package_version.update_way
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getUpdateWay() {
        return updateWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.update_way
     *
     * @param updateWay the value for package_version.update_way
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateWay(String updateWay) {
        this.updateWay = updateWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.descr
     *
     * @return the value of package_version.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.descr
     *
     * @param descr the value for package_version.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.create_time
     *
     * @return the value of package_version.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.create_time
     *
     * @param createTime the value for package_version.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_version.update_time
     *
     * @return the value of package_version.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_version.update_time
     *
     * @param updateTime the value for package_version.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}