package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class Package implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.alias
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table package
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.id
     *
     * @return the value of package.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.id
     *
     * @param id the value for package.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.name
     *
     * @return the value of package.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.name
     *
     * @param name the value for package.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.alias
     *
     * @return the value of package.alias
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.alias
     *
     * @param alias the value for package.alias
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.create_time
     *
     * @return the value of package.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.create_time
     *
     * @param createTime the value for package.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package.update_time
     *
     * @return the value of package.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package.update_time
     *
     * @param updateTime the value for package.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}