package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class PackageDownLoadInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_download_info.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_download_info.package_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer packageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_download_info.package_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer packageVersionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_download_info.key
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_download_info.download_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String downloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_download_info.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_download_info.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column package_download_info.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_download_info.id
     *
     * @return the value of package_download_info.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_download_info.id
     *
     * @param id the value for package_download_info.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_download_info.package_id
     *
     * @return the value of package_download_info.package_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getPackageId() {
        return packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_download_info.package_id
     *
     * @param packageId the value for package_download_info.package_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_download_info.package_version_id
     *
     * @return the value of package_download_info.package_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getPackageVersionId() {
        return packageVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_download_info.package_version_id
     *
     * @param packageVersionId the value for package_download_info.package_version_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setPackageVersionId(Integer packageVersionId) {
        this.packageVersionId = packageVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_download_info.key
     *
     * @return the value of package_download_info.key
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_download_info.key
     *
     * @param key the value for package_download_info.key
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_download_info.download_url
     *
     * @return the value of package_download_info.download_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_download_info.download_url
     *
     * @param downloadUrl the value for package_download_info.download_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_download_info.descr
     *
     * @return the value of package_download_info.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_download_info.descr
     *
     * @param descr the value for package_download_info.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_download_info.create_time
     *
     * @return the value of package_download_info.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_download_info.create_time
     *
     * @param createTime the value for package_download_info.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column package_download_info.update_time
     *
     * @return the value of package_download_info.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column package_download_info.update_time
     *
     * @param updateTime the value for package_download_info.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}