package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class Patch implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patch.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patch.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patch.alias
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patch.download_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String downloadUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patch.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patch.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patch.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patch.id
     *
     * @return the value of patch.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patch.id
     *
     * @param id the value for patch.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patch.name
     *
     * @return the value of patch.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patch.name
     *
     * @param name the value for patch.name
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patch.alias
     *
     * @return the value of patch.alias
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patch.alias
     *
     * @param alias the value for patch.alias
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patch.download_url
     *
     * @return the value of patch.download_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patch.download_url
     *
     * @param downloadUrl the value for patch.download_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patch.descr
     *
     * @return the value of patch.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patch.descr
     *
     * @param descr the value for patch.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patch.create_time
     *
     * @return the value of patch.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patch.create_time
     *
     * @param createTime the value for patch.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patch.update_time
     *
     * @return the value of patch.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patch.update_time
     *
     * @param updateTime the value for patch.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}