package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class PluginVersion implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_version.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_version.plugin_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer pluginId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_version.version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_version.build_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer buildId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_version.online_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String onlineUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_version.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_version.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plugin_version.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_version.id
     *
     * @return the value of plugin_version.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_version.id
     *
     * @param id the value for plugin_version.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_version.plugin_id
     *
     * @return the value of plugin_version.plugin_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getPluginId() {
        return pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_version.plugin_id
     *
     * @param pluginId the value for plugin_version.plugin_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setPluginId(Integer pluginId) {
        this.pluginId = pluginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_version.version
     *
     * @return the value of plugin_version.version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_version.version
     *
     * @param version the value for plugin_version.version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_version.build_id
     *
     * @return the value of plugin_version.build_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getBuildId() {
        return buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_version.build_id
     *
     * @param buildId the value for plugin_version.build_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setBuildId(Integer buildId) {
        this.buildId = buildId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_version.online_url
     *
     * @return the value of plugin_version.online_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getOnlineUrl() {
        return onlineUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_version.online_url
     *
     * @param onlineUrl the value for plugin_version.online_url
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setOnlineUrl(String onlineUrl) {
        this.onlineUrl = onlineUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_version.descr
     *
     * @return the value of plugin_version.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_version.descr
     *
     * @param descr the value for plugin_version.descr
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_version.create_time
     *
     * @return the value of plugin_version.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_version.create_time
     *
     * @param createTime the value for plugin_version.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plugin_version.update_time
     *
     * @return the value of plugin_version.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plugin_version.update_time
     *
     * @param updateTime the value for plugin_version.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}