package com.hujiang.mmp.model;

import java.io.Serializable;
import java.util.Date;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

public class PublishDimension implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_dimension.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_dimension.flow_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer flowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_dimension.flow_type
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer flowType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_dimension.type
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_dimension.value
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_dimension.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column publish_dimension.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_dimension.id
     *
     * @return the value of publish_dimension.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_dimension.id
     *
     * @param id the value for publish_dimension.id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_dimension.flow_id
     *
     * @return the value of publish_dimension.flow_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_dimension.flow_id
     *
     * @param flowId the value for publish_dimension.flow_id
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setFlowId(Integer flowId) {
        this.flowId = flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_dimension.flow_type
     *
     * @return the value of publish_dimension.flow_type
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getFlowType() {
        return flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_dimension.flow_type
     *
     * @param flowType the value for publish_dimension.flow_type
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setFlowType(Integer flowType) {
        this.flowType = flowType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_dimension.type
     *
     * @return the value of publish_dimension.type
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_dimension.type
     *
     * @param type the value for publish_dimension.type
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_dimension.value
     *
     * @return the value of publish_dimension.value
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_dimension.value
     *
     * @param value the value for publish_dimension.value
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_dimension.create_time
     *
     * @return the value of publish_dimension.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_dimension.create_time
     *
     * @param createTime the value for publish_dimension.create_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column publish_dimension.update_time
     *
     * @return the value of publish_dimension.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column publish_dimension.update_time
     *
     * @param updateTime the value for publish_dimension.update_time
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String toString() {
        return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
    }
}