package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.AppConfigFlow;
import com.hujiang.mmp.model.AppConfigFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppConfigFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(AppConfigFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(AppConfigFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(AppConfigFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(AppConfigFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<AppConfigFlow> selectByExample(AppConfigFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppConfigFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppConfigFlow lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppConfigFlow record, @Param("example") AppConfigFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") AppConfigFlow record, @Param("example") AppConfigFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(AppConfigFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_config_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(AppConfigFlow record);
}