package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.AppChannel;
import com.hujiang.mmp.model.AppChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(AppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(AppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(AppChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(AppChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<AppChannel> selectByExample(AppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppChannel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppChannel lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppChannel record, @Param("example") AppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") AppChannel record, @Param("example") AppChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(AppChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(AppChannel record);
}