package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.AppPackageFlow;
import com.hujiang.mmp.model.AppPackageFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppPackageFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(AppPackageFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(AppPackageFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(AppPackageFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(AppPackageFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<AppPackageFlow> selectByExample(AppPackageFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppPackageFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppPackageFlow lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppPackageFlow record, @Param("example") AppPackageFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") AppPackageFlow record, @Param("example") AppPackageFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(AppPackageFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_package_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(AppPackageFlow record);
}