package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.AppPatchFlow;
import com.hujiang.mmp.model.AppPatchFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppPatchFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(AppPatchFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(AppPatchFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(AppPatchFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(AppPatchFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<AppPatchFlow> selectByExample(AppPatchFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppPatchFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppPatchFlow lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppPatchFlow record, @Param("example") AppPatchFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") AppPatchFlow record, @Param("example") AppPatchFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(AppPatchFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_patch_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(AppPatchFlow record);
}