package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.AppPluginFlow;
import com.hujiang.mmp.model.AppPluginFlowExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AppPluginFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(AppPluginFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(AppPluginFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(AppPluginFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(AppPluginFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<AppPluginFlow> selectByExample(AppPluginFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppPluginFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    AppPluginFlow lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") AppPluginFlow record, @Param("example") AppPluginFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") AppPluginFlow record, @Param("example") AppPluginFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(AppPluginFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_plugin_flow
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(AppPluginFlow record);
}