package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.Channel;
import com.hujiang.mmp.model.ChannelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<Channel> selectByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    Channel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    Channel lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(Channel record);
}