package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.PackageDownLoadInfo;
import com.hujiang.mmp.model.PackageDownLoadInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PackageDownLoadInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(PackageDownLoadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(PackageDownLoadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(PackageDownLoadInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(PackageDownLoadInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<PackageDownLoadInfo> selectByExample(PackageDownLoadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    PackageDownLoadInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    PackageDownLoadInfo lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") PackageDownLoadInfo record, @Param("example") PackageDownLoadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") PackageDownLoadInfo record, @Param("example") PackageDownLoadInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(PackageDownLoadInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_download_info
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(PackageDownLoadInfo record);
}