package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.PackageVersion;
import com.hujiang.mmp.model.PackageVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PackageVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(PackageVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(PackageVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(PackageVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(PackageVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<PackageVersion> selectByExample(PackageVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    PackageVersion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    PackageVersion lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") PackageVersion record, @Param("example") PackageVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") PackageVersion record, @Param("example") PackageVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(PackageVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table package_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(PackageVersion record);
}