package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.Patch;
import com.hujiang.mmp.model.PatchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PatchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(PatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(PatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(Patch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(Patch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<Patch> selectByExample(PatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    Patch selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    Patch lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") Patch record, @Param("example") PatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") Patch record, @Param("example") PatchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(Patch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patch
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(Patch record);
}