package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.PluginVersion;
import com.hujiang.mmp.model.PluginVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PluginVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(PluginVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(PluginVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(PluginVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(PluginVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<PluginVersion> selectByExample(PluginVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    PluginVersion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    PluginVersion lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") PluginVersion record, @Param("example") PluginVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") PluginVersion record, @Param("example") PluginVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(PluginVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plugin_version
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(PluginVersion record);
}