package com.hujiang.mmp.prv.mapper;

import com.hujiang.mmp.model.PublishDimension;
import com.hujiang.mmp.model.PublishDimensionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PublishDimensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int countByExample(PublishDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByExample(PublishDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insert(PublishDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int insertSelective(PublishDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    List<PublishDimension> selectByExample(PublishDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    PublishDimension selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    PublishDimension lockByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExampleSelective(@Param("record") PublishDimension record, @Param("example") PublishDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByExample(@Param("record") PublishDimension record, @Param("example") PublishDimensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKeySelective(PublishDimension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table publish_dimension
     *
     * @mbggenerated Tue Aug 23 13:55:33 CST 2016
     */
    int updateByPrimaryKey(PublishDimension record);
}